"use strict";(()=>{function v(){return window.LUA_DATA||{level:1,totalXp:0,xpInLevel:0,xpForLevel:50,title:"Novice",streak:0,bestStreak:0,totalCards:0,todayXp:0,todayCards:0,todayCorrect:0,combo:0,badges:{}}}var i=v();function p(e){return e.xpForLevel<=0?100:Math.min(100,e.xpInLevel/e.xpForLevel*100)}function u(){let e=document.getElementById("lua-level-bar");if(!e)return;let t=i,a=e.querySelector(".lua-lb-level");a&&(a.textContent=`Lvl ${t.level}`);let o=e.querySelector(".lua-lb-title");o&&(o.textContent=t.title);let l=e.querySelector(".lua-lb-xp-fill");l&&(l.style.width=`${p(t)}%`);let r=e.querySelector(".lua-lb-xp-text");r&&(r.textContent=`${t.xpInLevel}/${t.xpForLevel} XP`);let n=e.querySelector(".lua-lb-streak");n&&(n.textContent=`\u{1F525} ${t.streak}`);let s=e.querySelector(".lua-lb-cards");s&&(s.textContent=`${t.todayCards} today`)}function d(e,t){let a=document.createElement("div");a.className="lua-xp-toast"+(t?" "+t:""),a.textContent=e,a.style.left="50%",a.style.top="50%",a.style.transform="translate(-50%, -50%)",document.body.appendChild(a),setTimeout(()=>a.remove(),1800)}function b(e){let t=document.createElement("div");t.className="lua-badge-toast",t.innerHTML=`
        <span class="lua-badge-icon">${e.icon}</span>
        <span class="lua-badge-info">
            <span class="lua-badge-label">Badge earned!</span>
            <span class="lua-badge-name">${e.name}</span>
        </span>
    `,document.body.appendChild(t),setTimeout(()=>t.remove(),3500)}function c(e,t){let a=document.createElement("div");a.className="lua-levelup-overlay",a.innerHTML=`
        <div class="lua-levelup-card">
            <div class="lua-levelup-icon">\u{1F389}</div>
            <div class="lua-levelup-label">Level Up!</div>
            <div class="lua-levelup-number">${e}</div>
            <div class="lua-levelup-title">${t}</div>
            <button class="lua-levelup-dismiss">Continue</button>
        </div>
    `,document.body.appendChild(a),a.addEventListener("click",o=>{(o.target===a||o.target.classList.contains("lua-levelup-dismiss"))&&a.remove()});try{window.LUA_CONFETTI()}catch{}}function y(){let e=document.createElement("canvas");e.style.cssText="position:fixed;inset:0;z-index:4000;pointer-events:none;",document.body.appendChild(e);let t=e.getContext("2d");e.width=window.innerWidth,e.height=window.innerHeight;let a=["#007AFF","#34C759","#FF9500","#FF3B30","#AF52DE","#FFD60A"],o=[];for(let n=0;n<80;n++)o.push({x:Math.random()*e.width,y:-10-Math.random()*200,vx:(Math.random()-.5)*6,vy:Math.random()*4+2,w:Math.random()*10+4,h:Math.random()*6+3,color:a[Math.floor(Math.random()*a.length)],rot:Math.random()*Math.PI*2,vr:(Math.random()-.5)*.3});let l=0;function r(){t.clearRect(0,0,e.width,e.height);for(let n of o)n.x+=n.vx,n.y+=n.vy,n.vy+=.08,n.rot+=n.vr,t.save(),t.translate(n.x,n.y),t.rotate(n.rot),t.fillStyle=n.color,t.fillRect(-n.w/2,-n.h/2,n.w,n.h),t.restore();l++,l<120?requestAnimationFrame(r):e.remove()}r()}window.LUA_CONFETTI=y;function m(e,t){let a=document.getElementById(e);if(!a)return;let o=Math.max(...t.map(r=>r.xp),1),l=t.map(r=>{let n=Math.max(2,r.xp/o*100),s=`${r.day}: ${r.xp} XP, ${r.cards} cards`;return`<div class="lua-chart-bar" style="height:${n}%" data-tooltip="${s}"></div>`}).join("");a.innerHTML=`<div class="lua-chart-bars">${l}</div>`}function g(e){let t=document.getElementById("lua-badges-grid");t&&(t.innerHTML=e.map(a=>`
            <div class="lua-badge-card ${a.earned?"earned":"locked"}">
                <div class="lua-badge-card-icon">${a.icon}</div>
                <div class="lua-badge-card-name">${a.name}</div>
                <div class="lua-badge-card-desc">${a.desc}</div>
            </div>
        `).join(""))}var f={onSummary(e){i=e,u()},onXpAwarded(e){i=e.summary,u();let t=e.xpDetail,a=`+${e.xp} XP`,o="";t.streak_mult>1?o="streak-bonus":t.combo_mult>1?o="combo":(t.speed_bonus>0||t.daily_bonus_pct>0)&&(o="bonus"),d(a,o),t.streak_mult>1&&setTimeout(()=>d(`\u{1F525} Streak Bonus: x${t.streak_mult}`,"streak-bonus"),400),t.combo_mult>1&&setTimeout(()=>d(`\u26A1 Combo: x${t.combo_mult}`,"combo"),400),e.badges&&e.badges.forEach((l,r)=>{setTimeout(()=>b(l),800+r*600)}),e.levelUp&&setTimeout(()=>c(e.level,e.newTitle),600)},onLevelUp(e,t){c(e,t)},onWeekStats(e){m("lua-week-chart",e)},onMonthStats(e){m("lua-month-chart",e)},onBadges(e){g(e)}};window.Lua=f;i=v();u();})();
